### PR TITLE
Added plotting functions and doc strings

### PR DESCRIPTION
**Pull request by ajtoler**
Added magnetization and grid plotting and some doc strings. (I think Ryan's are more detailed so I can remove mine if needed. Still working on specific heat calculations, will continue on Thursday night.

### CODE REVIEW

**Comment by rpsimeon34** [comment]
Thanks for adding this! The plotting functionality looks good. I'd recommend removing num_iter as a parameter in plot_grid, since it's unused.

Also, I'm happy to go with your docstrings, since they include more physics details. The only change I'd suggest there is adding back tics (``) for code blocks and such, making use of reStructured Text.

**Comment by mmaroun0** [comment]
Chefs, what's the status on this? How will things get resolved? There may be some new conflicts with some other changes that I snuck in before, but can it be pulled in?

**Comment by ajtoler** [comment]
I will make it compatible with the master branch tomorrow.

**Comment by mmaroun0** [comment]
thank you chef

**Comment by mirarenee** [comment]
Resolved conflicts with main branch

**Pull request merged**
